// =============================================
// Default settings for all overlay widget types
// =============================================

// Gift Alert
export const defaultGiftAlertSettings = {
  trigger_mode: "any_gift" as "any_gift" | "specific_gift" | "value_threshold" | "combo" | "milestone",
  specific_gift_type: "",
  value_threshold: 100,
  combo_threshold: 5,
  milestone_total: 1000,
  animation_style: "bounce" as "slide" | "bounce" | "explosion" | "flip_3d" | "glitch",
  duration: 5,
  entry_animation: "scale_up" as "scale_up" | "slide_left" | "slide_right" | "slide_top" | "fade",
  exit_animation: "fade" as "fade" | "slide_out" | "scale_down" | "dissolve",
  gift_image_size: 64,
  username_font: "heading" as "heading" | "mono" | "sans",
  glow_intensity: 50,
  shadow_depth: 30,
  border_glow: true,
  accent_color: "160 100% 45%",
  sound_url: "",
  sound_volume: 80,
  sound_delay: 0,
  sound_loop: false,
  combo_sound_override: "",
  queue_enabled: true,
  priority_alerts: true,
  max_on_screen: 3,
  anti_spam_throttle: 2,
  alert_cooldown: 1,
  animation_speed: 1,
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Chat Box
export const defaultChatBoxSettings = {
  display_mode: "cyber" as "minimal" | "twitch" | "cyber" | "glass",
  message_fade_time: 30,
  max_messages: 8,
  username_color_auto: true,
  show_badges: true,
  emote_scale: 1.2,
  highlight_gifts: true,
  highlight_keywords: "",
  highlight_moderators: true,
  auto_scroll: true,
  message_animation: "slide" as "slide" | "fade" | "pop" | "typewriter",
  shadow_depth: 20,
  font_size: 13,
  font_family: "sans" as "sans" | "mono" | "heading",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
  accent_color: "160 100% 45%",
};

// Like Alert
export const defaultLikeAlertSettings = {
  animation_style: "hearts_rise" as "hearts_rise" | "pulse_burst" | "neon_wave" | "sparkle_trail" | "vortex" | "ripple_glow",
  duration: 4,
  icon_size: 48,
  glow_intensity: 60,
  particle_count: 12,
  color_mode: "warm" as "warm" | "cool" | "rainbow" | "mono",
  show_count: true,
  count_style: "animated" as "animated" | "static" | "milestone",
  milestone_interval: 100,
  milestone_animation: "confetti" as "confetti" | "flash" | "shake" | "explode",
  username_visible: true,
  combo_detection: true,
  combo_multiplier_visual: true,
  entry_animation: "float_up" as "float_up" | "slide_in" | "scale_pop" | "spiral",
  exit_animation: "fade_up" as "fade_up" | "dissolve" | "shrink" | "fly_away",
  sound_volume: 70,
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
  accent_color: "350 90% 55%",
  queue_enabled: true,
  max_on_screen: 5,
  anti_spam_throttle: 0.5,
  animation_speed: 1,
};

// Follow Alert
export const defaultFollowAlertSettings = {
  animation_style: "spotlight" as "spotlight" | "badge_drop" | "neon_slide" | "hologram" | "portal" | "glitch_in",
  duration: 5,
  icon_size: 56,
  glow_intensity: 50,
  show_avatar: true,
  avatar_style: "circle" as "circle" | "hexagon" | "rounded_square",
  welcome_text: "just followed!",
  username_font: "heading" as "heading" | "mono" | "sans",
  card_style: "glass" as "glass" | "solid" | "neon_border" | "gradient" | "minimal",
  entry_animation: "drop_bounce" as "drop_bounce" | "slide_right" | "zoom_in" | "typewriter" | "flip",
  exit_animation: "fade" as "fade" | "slide_out" | "scale_down" | "glitch_out",
  sound_volume: 80,
  counter_visible: true,
  streak_detection: true,
  streak_threshold: 3,
  streak_animation: "rainbow" as "rainbow" | "shake" | "grow",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
  accent_color: "160 100% 45%",
  queue_enabled: true,
  max_on_screen: 3,
  anti_spam_throttle: 1,
  animation_speed: 1,
};

// Share Alert
export const defaultShareAlertSettings = {
  animation_style: "rocket_launch" as "rocket_launch" | "shockwave" | "neon_burst" | "paper_plane" | "warp_speed" | "sonic_boom",
  duration: 5,
  icon_size: 52,
  glow_intensity: 55,
  show_share_count: true,
  batch_detection: true,
  batch_threshold: 5,
  milestone_triggers: true,
  milestone_interval: 50,
  milestone_animation: "explosion" as "explosion" | "fireworks" | "rainbow_wave",
  username_visible: true,
  card_style: "cyber" as "cyber" | "glass" | "minimal" | "gradient",
  entry_animation: "burst" as "burst" | "slide" | "zoom" | "spiral",
  exit_animation: "fade" as "fade" | "fly_out" | "dissolve",
  sound_volume: 75,
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
  accent_color: "200 100% 55%",
  queue_enabled: true,
  max_on_screen: 3,
  anti_spam_throttle: 1,
  animation_speed: 1,
};

// Like Counter
export const defaultLikeCounterSettings = {
  display_mode: "numeric" as "numeric" | "milestone" | "progress_ring" | "horizontal_bar" | "neon_counter",
  font_family: "heading" as "heading" | "mono" | "sans",
  font_weight: "bold" as "normal" | "bold" | "black",
  font_size: 48,
  glow_strength: 60,
  animated_increment: true,
  smoothing_effect: true,
  count_speed: 500,
  milestone_interval: 1000,
  milestone_animation: "confetti" as "confetti" | "flash" | "shake" | "explode",
  rolling_number: true,
  confetti_on_milestone: true,
  particle_burst: true,
  sound_on_milestone: true,
  reset_daily: false,
  accent_color: "280 100% 65%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Follower Goal
export const defaultFollowerGoalSettings = {
  start_value: 0,
  target_value: 1000,
  current_value: 0,
  auto_detect: false,
  display_style: "glass_bar" as "glass_bar" | "neon_gradient" | "circular" | "minimal" | "liquid_fill",
  bar_height: 32,
  glow_color: "160 100% 45%",
  text_position: "inside" as "inside" | "above" | "below" | "hidden",
  show_percentage: true,
  auto_hide_complete: false,
  completion_animation: "confetti" as "confetti" | "flash" | "fireworks" | "none",
  multi_stage: false,
  milestone_alerts: true,
  time_based_mode: false,
  auto_reset_stream: false,
  title_text: "Follower Goal",
  accent_color: "160 100% 45%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Viewer Count
export const defaultViewerCountSettings = {
  display_mode: "live_number" as "live_number" | "mini_graph" | "badge" | "pulse_dot",
  font_size: 36,
  font_family: "heading" as "heading" | "mono" | "sans",
  spike_animation: true,
  pulse_on_increase: true,
  drop_animation: true,
  peak_tracker: true,
  session_high_highlight: true,
  show_average: false,
  time_window: 60,
  spike_threshold: 50,
  icon_visible: true,
  label_text: "viewers",
  accent_color: "45 100% 55%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Leaderboard
export const defaultLeaderboardSettings = {
  leaderboard_type: "gifters" as "gifters" | "likers" | "fans",
  time_range: "session" as "session" | "all_time" | "daily" | "weekly",
  display_mode: "vertical" as "vertical" | "ticker" | "podium" | "spotlight",
  max_entries: 5,
  rank_badge_style: "number" as "number" | "medal" | "crown" | "neon",
  crown_for_first: true,
  glow_per_rank: true,
  animated_rank_change: true,
  auto_refresh: 30,
  sliding_transitions: true,
  show_values: true,
  show_avatars: true,
  accent_color: "45 100% 55%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Stream Timer
export const defaultStreamTimerSettings = {
  display_mode: "digital" as "digital" | "neon_segmented" | "minimal_dot",
  font_family: "mono" as "heading" | "mono" | "sans",
  font_size: 42,
  start_on_connect: true,
  show_hours: true,
  show_seconds: true,
  glow_animation: true,
  glow_intensity: 50,
  milestone_notifications: true,
  milestone_interval: 60,
  session_memory: true,
  auto_hide_offline: true,
  label_text: "LIVE",
  show_label: true,
  accent_color: "0 100% 60%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Custom Text
export const defaultCustomTextSettings = {
  text_content: "Welcome to {streamer}'s stream!",
  font_family: "heading" as "heading" | "mono" | "sans",
  font_size: 28,
  font_weight: "bold" as "normal" | "bold" | "black",
  text_align: "center" as "left" | "center" | "right",
  animated_gradient: true,
  gradient_colors: "280 100% 65%, 200 100% 55%",
  gradient_speed: 3,
  background_blur: 0,
  background_opacity: 0,
  text_shadow: true,
  shadow_color: "0 0% 0%",
  shadow_blur: 10,
  variable_binding: true,
  refresh_interval: 10,
  scroll_mode: "none" as "none" | "horizontal" | "vertical",
  scroll_speed: 30,
  accent_color: "280 100% 65%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// TTS Overlay
export const defaultTTSSettings = {
  voice_id: "JBFqnCBsd6RMkjVDRZzb",
  volume: 80,
  speed: 1.0,
  show_bubble: true,
  bubble_position: "bottom-center" as "bottom-center" | "bottom-left" | "bottom-right" | "top-center",
  bubble_style: "glass" as "glass" | "neon" | "minimal",
  show_soundwave: true,
  show_avatar: true,
  accent_color: "160 100% 45%",
  transparent_bg: true,
  dark_bg: false,
  fps_limit: 60,
  custom_css: "",
};

// Map type → defaults
export const overlayDefaultsMap: Record<string, Record<string, any>> = {
  gift_alert: defaultGiftAlertSettings,
  chat_box: defaultChatBoxSettings,
  like_alert: defaultLikeAlertSettings,
  follow_alert: defaultFollowAlertSettings,
  share_alert: defaultShareAlertSettings,
  like_counter: defaultLikeCounterSettings,
  follower_goal: defaultFollowerGoalSettings,
  viewer_count: defaultViewerCountSettings,
  leaderboard: defaultLeaderboardSettings,
  stream_timer: defaultStreamTimerSettings,
  custom_text: defaultCustomTextSettings,
  tts: defaultTTSSettings,
};
