
-- Insert feature flags for all overlay routes that don't already exist
INSERT INTO public.feature_flags (feature_key, label, section, is_visible, description, badge)
VALUES 
  ('/tts-overlay', 'Text-to-Speech (TTS)', 'Overlays', true, 'Floating notification bubble with soundwave animation.', ''),
  ('/chat-overlay-widget', 'TikTok Chat Overlay', 'Overlays', true, 'Stacked chat messages with smooth slide-in animations.', ''),
  ('/sound-alert-overlay', 'Sound Alert Overlay', 'Overlays', true, 'Center-screen animated alert with neon rings.', ''),
  ('/ticker-overlay', 'Notifications Ticker', 'Overlays', true, 'Scrolling event ticker bar.', ''),
  ('/like-follow-overlay', 'Like/Follow Overlay', 'Overlays', true, 'Elegant floating notifications with particles.', ''),
  ('/gift-alert-overlay', 'Gift Alert Overlay', 'Overlays', true, 'Animated gift alerts with glow pulse.', ''),
  ('/follow-alert-overlay', 'Follow Alert', 'Overlays', true, 'Clean follow notification with avatar.', ''),
  ('/share-alert-overlay', 'Share Alert', 'Overlays', true, 'Stream share notification with animation.', ''),
  ('/like-alert-overlay', 'Like Alert', 'Overlays', true, 'Floating hearts animation from likes.', ''),
  ('/gift-combo-overlay', 'Super Gift Combo', 'Overlays', true, 'Stacking combo counter with tiers.', ''),
  ('/gift-firework-overlay', 'Gift Firework', 'Overlays', true, 'Cinematic firework explosions from gifts.', ''),
  ('/goal-progress-overlay', 'Goal Progress Bar', 'Overlays', true, 'Animated progress bars for goals.', ''),
  ('/follower-goal-overlay', 'Follower Goal', 'Overlays', true, 'Animated follower goal bar.', ''),
  ('/coin-jar-overlay', 'Coin Jar', 'Overlays', true, 'Visual jar that fills with gifts.', ''),
  ('/progress-race-overlay', 'Progress Race', 'Overlays', true, 'Teams race powered by gifts and likes.', ''),
  ('/viewer-count-overlay', 'Viewer Count', 'Overlays', true, 'Live viewer count with graph mode.', ''),
  ('/like-counter-overlay', 'Like Counter', 'Overlays', true, 'Real-time like counter with ring.', ''),
  ('/leaderboard-overlay', 'Leaderboard', 'Overlays', true, 'Live top gifters leaderboard.', ''),
  ('/stream-timer-overlay', 'Stream Timer', 'Overlays', true, 'Digital countdown/count-up timer.', ''),
  ('/custom-text-overlay', 'Custom Text', 'Overlays', true, 'Dynamic text with variable binding.', ''),
  ('/social-rotator-overlay', 'Social Media Rotator', 'Overlays', true, 'Animated 3D carousel of social links.', ''),
  ('/sound-reactive-overlay', 'Sound Reactive', 'Overlays', true, 'Audio visualizer synced to audio.', ''),
  ('/gift-actions-overlay', 'Gift Actions Slider', 'Overlays', true, 'Scrolling carousel of gift actions.', ''),
  ('/spin-wheel-overlay', 'Spin Wheel', 'Overlays', true, 'Gift-triggered spin wheel.', ''),
  ('/battle-royale-overlay', 'Battle Royale', 'Overlays', true, 'Viewer avatars fight on screen.', ''),
  ('/slot-machine-overlay', 'Slot Machine', 'Overlays', true, 'Gift-triggered 3-reel slot machine.', ''),
  ('/vote-battle-overlay', 'Vote Battle', 'Overlays', true, 'Two-sided animated vote bar.', ''),
  ('/stream-buddies-overlay', 'Stream Buddies', 'Overlays', true, 'Pixel-art avatars of supporters.', ''),
  ('/pacman-overlay', 'Pac-Man LIVE', 'Overlays', true, 'Interactive Pac-Man controlled by chat.', ''),
  ('/promo-overlay', 'Promo Overlay', 'Overlays', true, 'Branded promo overlay with CTA.', ''),
  ('/stream-border-overlay', 'Stream Border', 'Overlays', true, 'Premium animated borders.', ''),
  ('/webcam-frame-overlay', 'Webcam Frame', 'Overlays', true, 'Animated webcam frames.', ''),
  ('/video-cam-frame-overlay', 'Video Cam Frame', 'Overlays', true, 'Animated WebM webcam frame.', ''),
  ('/video-label-bar-overlay', 'Video Label Bar', 'Overlays', true, 'Animated WebM label bar.', ''),
  ('/animated-bg-overlay', 'Animated Background', 'Overlays', true, 'Looping animated backgrounds.', ''),
  ('/studio-bg-overlay', 'Studio Backgrounds', 'Overlays', true, 'Premium animated room backgrounds.', '')
ON CONFLICT DO NOTHING;
